<!DOCTYPE html>

<html>

<head>

<meta charset="utf-8" />
<meta name="generator" content="pandoc" />
<meta http-equiv="X-UA-Compatible" content="IE=EDGE" />




<title>—</title>

<script src="site_libs/header-attrs-2.6/header-attrs.js"></script>
<script src="site_libs/jquery-1.11.3/jquery.min.js"></script>
<meta name="viewport" content="width=device-width, initial-scale=1" />
<link href="site_libs/bootstrap-3.3.5/css/united.min.css" rel="stylesheet" />
<script src="site_libs/bootstrap-3.3.5/js/bootstrap.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/html5shiv.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/respond.min.js"></script>
<script src="site_libs/navigation-1.1/tabsets.js"></script>
<link href="site_libs/highlightjs-9.12.0/default.css" rel="stylesheet" />
<script src="site_libs/highlightjs-9.12.0/highlight.js"></script>

<style type="text/css">
  code{white-space: pre-wrap;}
  span.smallcaps{font-variant: small-caps;}
  span.underline{text-decoration: underline;}
  div.column{display: inline-block; vertical-align: top; width: 50%;}
  div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
  ul.task-list{list-style: none;}
    </style>

<style type="text/css">code{white-space: pre;}</style>
<style type="text/css">
  pre:not([class]) {
    background-color: white;
  }
</style>
<script type="text/javascript">
if (window.hljs) {
  hljs.configure({languages: []});
  hljs.initHighlightingOnLoad();
  if (document.readyState && document.readyState === "complete") {
    window.setTimeout(function() { hljs.initHighlighting(); }, 0);
  }
}
</script>



<style type="text/css">
h1 {
  font-size: 34px;
}
h1.title {
  font-size: 38px;
}
h2 {
  font-size: 30px;
}
h3 {
  font-size: 24px;
}
h4 {
  font-size: 18px;
}
h5 {
  font-size: 16px;
}
h6 {
  font-size: 12px;
}
.table th:not([align]) {
  text-align: left;
}
</style>


<link rel="stylesheet" href="style.css" type="text/css" />



<style type = "text/css">
.main-container {
  max-width: 940px;
  margin-left: auto;
  margin-right: auto;
}
code {
  color: inherit;
  background-color: rgba(0, 0, 0, 0.04);
}
img {
  max-width:100%;
}
.tabbed-pane {
  padding-top: 12px;
}
.html-widget {
  margin-bottom: 20px;
}
button.code-folding-btn:focus {
  outline: none;
}
summary {
  display: list-item;
}
</style>


<style type="text/css">
/* padding for bootstrap navbar */
body {
  padding-top: 51px;
  padding-bottom: 40px;
}
/* offset scroll position for anchor links (for fixed navbar)  */
.section h1 {
  padding-top: 56px;
  margin-top: -56px;
}
.section h2 {
  padding-top: 56px;
  margin-top: -56px;
}
.section h3 {
  padding-top: 56px;
  margin-top: -56px;
}
.section h4 {
  padding-top: 56px;
  margin-top: -56px;
}
.section h5 {
  padding-top: 56px;
  margin-top: -56px;
}
.section h6 {
  padding-top: 56px;
  margin-top: -56px;
}
.dropdown-submenu {
  position: relative;
}
.dropdown-submenu>.dropdown-menu {
  top: 0;
  left: 100%;
  margin-top: -6px;
  margin-left: -1px;
  border-radius: 0 6px 6px 6px;
}
.dropdown-submenu:hover>.dropdown-menu {
  display: block;
}
.dropdown-submenu>a:after {
  display: block;
  content: " ";
  float: right;
  width: 0;
  height: 0;
  border-color: transparent;
  border-style: solid;
  border-width: 5px 0 5px 5px;
  border-left-color: #cccccc;
  margin-top: 5px;
  margin-right: -10px;
}
.dropdown-submenu:hover>a:after {
  border-left-color: #ffffff;
}
.dropdown-submenu.pull-left {
  float: none;
}
.dropdown-submenu.pull-left>.dropdown-menu {
  left: -100%;
  margin-left: 10px;
  border-radius: 6px 0 6px 6px;
}
</style>

<script>
// manage active state of menu based on current page
$(document).ready(function () {
  // active menu anchor
  href = window.location.pathname
  href = href.substr(href.lastIndexOf('/') + 1)
  if (href === "")
    href = "index.html";
  var menuAnchor = $('a[href="' + href + '"]');

  // mark it active
  menuAnchor.parent().addClass('active');

  // if it's got a parent navbar menu mark it active as well
  menuAnchor.closest('li.dropdown').addClass('active');
});
</script>

<!-- tabsets -->

<style type="text/css">
.tabset-dropdown > .nav-tabs {
  display: inline-table;
  max-height: 500px;
  min-height: 44px;
  overflow-y: auto;
  background: white;
  border: 1px solid #ddd;
  border-radius: 4px;
}

.tabset-dropdown > .nav-tabs > li.active:before {
  content: "";
  font-family: 'Glyphicons Halflings';
  display: inline-block;
  padding: 10px;
  border-right: 1px solid #ddd;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li.active:before {
  content: "&#xe258;";
  border: none;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open:before {
  content: "";
  font-family: 'Glyphicons Halflings';
  display: inline-block;
  padding: 10px;
  border-right: 1px solid #ddd;
}

.tabset-dropdown > .nav-tabs > li.active {
  display: block;
}

.tabset-dropdown > .nav-tabs > li > a,
.tabset-dropdown > .nav-tabs > li > a:focus,
.tabset-dropdown > .nav-tabs > li > a:hover {
  border: none;
  display: inline-block;
  border-radius: 4px;
  background-color: transparent;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li {
  display: block;
  float: none;
}

.tabset-dropdown > .nav-tabs > li {
  display: none;
}
</style>

<!-- code folding -->




</head>

<body>


<div class="container-fluid main-container">




<div class="navbar navbar-default  navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="index.html">Ciencia de datos</a>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
        <li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
    Instalar R
     
    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu" role="menu">
    <li>
      <a href="instalar-r.html">Instalar R</a>
    </li>
    <li>
      <a href="instalar-rtools.html">Instalar Rtools</a>
    </li>
    <li>
      <a href="recursos.html">Recursos de R</a>
    </li>
    <li>
      <a href="swirl.html">Aprender R con SWIRL</a>
    </li>
  </ul>
</li>
<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
    Lenguaje R
     
    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu" role="menu">
    <li>
      <a href="recursos.html">Recursos de R</a>
    </li>
    <li>
      <a href="Vectores.html">Vectores</a>
    </li>
    <li>
      <a href="estructuras-de-control.html">Estructuras de control</a>
    </li>
    <li>
      <a href="marcos-de-datos.html">Marcos de datos</a>
    </li>
    <li>
      <a href="marcos-de-datos-con-dplyr.html">Marcos de datos con dplyr</a>
    </li>
    <li>
      <a href="descargar-salvar-recuperar.html">Descargar / Salvar / Recuperar</a>
    </li>
    <li>
      <a href="valores-perdidos.html">Valores perdidos</a>
    </li>
    <li>
      <a href="directorios.html">Listar directorios</a>
    </li>
    <li>
      <a href="expresiones-regulares.html">Expresiones regulares</a>
    </li>
    <li>
      <a href="fechas.html">Fechas</a>
    </li>
    <li>
      <a href="muestras-aleatorias.html">Muestras aleatorias</a>
    </li>
    <li>
      <a href="graficos-ggplot2.html">Gráficos</a>
    </li>
  </ul>
</li>
<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
    Obtener datos
     
    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu" role="menu">
    <li>
      <a href="leer-hojas-excel.html">Leer hojas Excel</a>
    </li>
    <li>
      <a href="leer-ficheros-xml.html">Leer ficheros XML</a>
    </li>
    <li>
      <a href="leer-ficheros-html.html">Leer ficheros HTML</a>
    </li>
    <li>
      <a href="leer-twitter.html">Leer Twitter</a>
    </li>
    <li>
      <a href="leer-bases-de-datos-sql.html">Leer bases de datos SQL</a>
    </li>
    <li>
      <a href="leer-bases-de-datos-no-sql.html">Leer bases de datos No SQL</a>
    </li>
  </ul>
</li>
<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
    R Studio
     
    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu" role="menu">
    <li>
      <a href="paquete-rmarkdown.html">R MarkDown</a>
    </li>
  </ul>
</li>
<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
    Estadística
     
    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu" role="menu">
    <li>
      <a href="ley-grandes-numeros.html">La ley de los grandes números</a>
    </li>
    <li>
      <a href="estadistica-descriptiva.html">Estadística descriptiva</a>
    </li>
    <li>
      <a href="prueba-t-student.html">La prueba t de Student</a>
    </li>
  </ul>
</li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        
      </ul>
    </div><!--/.nav-collapse -->
  </div><!--/.container -->
</div><!--/.navbar -->

<div class="fluid-row" id="header">



<h1 class="title toc-ignore">—</h1>

</div>


<pre class="r"><code>library(ggplot2)
library(dplyr)
tamano_muestral = 10000 #tamaño muestral (diez mil)</code></pre>
<div id="la-distribución-binomial-lanzar-un-dado-90-veces" class="section level3">
<h3>La distribución binomial: lanzar un dado 90 veces</h3>
<p>Todo experimento consiste en realizar una actividad y, en el curso de ella, medir <em>algo.</em> Si repetimos el experimento muchas veces (o si lo realizamos sobre muchos individuos) vamos obteniendo una muestra de resultados. A este número de veces que se repite el experimento se le llama <strong>tamaño muestral</strong>.</p>
<p>En este caso:</p>
<ul>
<li>Actividad: lanzar un dado 90 veces.<br />
</li>
<li>Medida: contar cuantas veces sale el “6”. Cómo mínimo, serán 0 veces y, como máximo, 90 veces.<br />
</li>
<li>Repeticiones del experimento: 10000 veces.</li>
</ul>
<p>La función “rbinom” realiza todo esto por nosotros. Sus parámetros son:</p>
<ul>
<li>size: número de veces que lanzamos el dado, que es 90.</li>
<li>prob: probabilidad teórica de que salga el “6” al lanzar el dado una sóla vez, que es 1/6 porque el dado tiene 6 caras.</li>
<li>n: número de veces que repetimos el experimento, que es 10000.</li>
</ul>
<pre class="r"><code>my_n = tamano_muestral
my_size = 90
my_prob = 1/6
muestra &lt;- rbinom(n=my_n, size=my_size, prob=my_prob)</code></pre>
<p>No podemos mostrar los resultados de los 10000 experimentos pero sí de los primeros:</p>
<pre class="r"><code>head(muestra, 30)</code></pre>
<pre><code>##  [1] 21 16 17 16 22 20 12 20  9 20 18 18 13 10 13 13 17 17  8 17 23 14 17 14 16
## [26] 15 19 11 14 21</code></pre>
<p>Podemos recoger en una tabla cuantas veces ha salido cada resultado:</p>
<pre class="r"><code>df &lt;- data.frame(nro_seises = muestra) %&gt;% 
    group_by(nro_seises) %&gt;% 
    summarise(veces = n()) %&gt;%
    arrange(-veces)
df</code></pre>
<pre><code>## # A tibble: 26 x 2
##    nro_seises veces
##         &lt;int&gt; &lt;int&gt;
##  1         14  1139
##  2         15  1095
##  3         13  1043
##  4         16  1012
##  5         17   885
##  6         12   871
##  7         18   748
##  8         11   591
##  9         19   546
## 10         20   441
## # ... with 16 more rows</code></pre>
<p>El histograma muestra, básicamente, esa tabla en forma gráfica:</p>
<pre class="r"><code>ggplot() + 
    geom_histogram(aes(x = muestra),
                   color = &quot;white&quot;, 
                   fill = &quot;orange&quot;, 
                   binwidth = 1) +
    labs(title = &quot;Histograma&quot;,
         x = &quot;Número de seises&quot;,
         y = &quot;Veces que hemos contado ese número de seises&quot;)</code></pre>
<p><img src="ley-grandes-numeros_files/figure-html/unnamed-chunk-5-1.png" width="672" /></p>
<p>Vemos que el resultado más repetido es 14, que ha ocurrido 1139 veces. Como el máximo de veces que podía repetirse era 10000, esto supone una proporción de 0.1139 o un porcentaje del 11.39%. A esta proporción se le llama <strong>frecuencia</strong> del resultado 14.</p>
<p>Podemos recoger en una tabla las frecuencias de todos los resultados. A esta tabla se la llama la <strong>distribución</strong> de resultados del experimento.</p>
<pre class="r"><code>distri_bin &lt;- mutate(df, frecuencia = round(veces / my_n,4))
distri_bin &lt;- select(distri_bin, nro_seises, frecuencia)
distri_bin</code></pre>
<pre><code>## # A tibble: 26 x 2
##    nro_seises frecuencia
##         &lt;int&gt;      &lt;dbl&gt;
##  1         14     0.114 
##  2         15     0.110 
##  3         13     0.104 
##  4         16     0.101 
##  5         17     0.0885
##  6         12     0.0871
##  7         18     0.0748
##  8         11     0.0591
##  9         19     0.0546
## 10         20     0.0441
## # ... with 16 more rows</code></pre>
<div id="abstracción" class="section level4">
<h4>Abstracción</h4>
<p>Cualquier experimento que se haga para medir <em>algo</em> producirá, en última instancia, una tabla de distribución de resultados. Más concisamente, se puede decir que todo experimento se resume en una distribución.</p>
<p>Si la distribución de un experimento coincide con la que acabamos de obtener (mismos resultados y misma frecuencia para cada resultado, salvo quizás el último decimal en algunos casos) diremos que el experimento indica que <em>lo que se está midiendo</em> sigue una distribución binomial de tamaño 90 y probabilidad 1/6.</p>
<p>Por ejemplo, si medimos la edad de las personas ingresadas en un hospital podría ser que saliera la tabla anterior (los niños de 14 años serían, en particular, los más habituales). Diríamos que la edad de las personas internadas en ese hospital sigue una distribución binomial de tamaño 90 y probabilidad 1/6.</p>
<p>Obviamente, podemos decir que el número de “6s”" que salen al tirar 90 veces un dado sigue una distribución binomial de tamaño 90 y probabilidad 1/6.</p>
<p>Otros ejemplos serían:</p>
<ul>
<li>El número de “caras” que salen al lanzar una moneda 100 veces sigue una distribución binomial de tamaño 100 y probabilidad 1/2.<br />
</li>
<li>El número de “ases de corazones” que salen al sacar una carta 100 veces de una baraja de poker (la carta se devuelve tras cada extracción y el mazo se mezcla) sigue una distribución binomial de tamaño 100 y probabilidad 1/52.</li>
</ul>
</div>
</div>
<div id="la-distribución-normal-medir-una-barra-de-5m-con-un-aparato-cuyo-margen-de-error-es-25cm" class="section level3">
<h3>La distribución normal: medir una barra de 5m con un aparato cuyo margen de error es 25cm</h3>
<p>Todo experimento consiste en realizar una actividad y, en el curso de ella, medir <em>algo</em>. Si repetimos el experimento muchas veces (o si lo realizamos sobre muchos individuos) vamos obteniendo una muestra de resultados. A este número de veces que se repite el experimento se le llama <strong>tamaño muestral</strong>.</p>
<p>En este caso:</p>
<ul>
<li>Actividad: Medir una barra cuya longitud sabemos que es 5 metros con un aparato cuya precisión es de 25 cm, es decir, 0.25 metros.<br />
</li>
<li>Medida: la implícita en la actividad.</li>
<li>Repeticiones del experimento:10000 veces.</li>
</ul>
<p>La función “rnorm” realiza el experimento por nosotros. Sus parámetros son:</p>
<ul>
<li>mean: la longitud verdadera de la barra, que es 5</li>
<li>sd: el margen de error del aparato de medida, que es 0.25</li>
<li>n: número de veces que repetimos el proceso de medición, que es 10000.</li>
</ul>
<pre class="r"><code>my_n = tamano_muestral
my_mean = 5
my_sd = 0.25
muestra &lt;- round( rnorm(n=my_n, mean=my_mean, sd=my_sd) ,2)</code></pre>
<p>No podemos mostrar los resultados de los 10000 experimentos pero sí de los primeros:</p>
<pre class="r"><code>head(muestra, 30)</code></pre>
<pre><code>##  [1] 5.19 4.94 4.66 4.69 4.97 5.47 4.87 4.76 4.85 5.14 4.90 4.69 4.97 4.99 5.39
## [16] 5.16 5.02 4.90 5.20 5.29 4.90 5.03 5.44 5.26 5.35 5.27 5.35 4.85 4.58 5.07</code></pre>
<p>Podemos recoger en una tabla cuantas veces ha salido cada resultado:</p>
<pre class="r"><code>df &lt;- data.frame(medidas = muestra) %&gt;% 
    group_by(medidas) %&gt;% 
    summarise(veces = n()) %&gt;%
    arrange(-veces)
df</code></pre>
<pre><code>## # A tibble: 169 x 2
##    medidas veces
##      &lt;dbl&gt; &lt;int&gt;
##  1    4.96   177
##  2    4.94   176
##  3    5.07   172
##  4    4.91   169
##  5    4.93   165
##  6    4.98   165
##  7    5.01   164
##  8    5.03   164
##  9    5.05   163
## 10    5.1    154
## # ... with 159 more rows</code></pre>
<p>El histograma muestra, básicamente, esa tabla en forma gráfica:</p>
<pre class="r"><code>ggplot() + 
    geom_histogram(aes(x = muestra),
                   color = &quot;white&quot;, 
                   fill = &quot;orange&quot;, 
                   binwidth = 0.01) +
    labs(title = &quot;Histograma&quot;,
         x = &quot;Medidas&quot;,
         y = &quot;Veces que ha salido esa medida&quot;)</code></pre>
<p><img src="ley-grandes-numeros_files/figure-html/unnamed-chunk-11-1.png" width="672" /></p>
<p>Vemos que el resultado más repetido es 4.96, que ha ocurrido 177 veces. Como el máximo de veces que podía repetirse era 10000, esto supone una proporción de 0.0177 o un porcentaje del 1.77%. A esta proporción se le llama <strong>frecuencia</strong> del resultado 4.96.</p>
<p>Podemos recoger en una tabla las frecuencias de todos los resultados. A esta tabla se la llama la <strong>distribución</strong> de resultados del experimento.</p>
<pre class="r"><code>distri_nor &lt;- mutate(df, frecuencia = round(veces / my_n,4))
distri_nor &lt;- select(distri_nor, medidas, frecuencia)
distri_nor</code></pre>
<pre><code>## # A tibble: 169 x 2
##    medidas frecuencia
##      &lt;dbl&gt;      &lt;dbl&gt;
##  1    4.96     0.0177
##  2    4.94     0.0176
##  3    5.07     0.0172
##  4    4.91     0.0169
##  5    4.93     0.0165
##  6    4.98     0.0165
##  7    5.01     0.0164
##  8    5.03     0.0164
##  9    5.05     0.0163
## 10    5.1      0.0154
## # ... with 159 more rows</code></pre>
<div id="abstracción-1" class="section level4">
<h4>Abstracción</h4>
<p>Cualquier experimento que se haga para medir <em>algo</em> producirá, en última instancia, una tabla de distribución de resultados. Más concisamente, se puede decir que todo experimento se resume en una distribución.</p>
<p>Si la distribución de un experimento coincide con la que acabamos de obtener (mismos resultados y misma frecuencia para cada resultado, salvo quizás el último decimal en algunos casos) diremos que el experimento indica que <em>lo que se está midiendo</em> sigue una distribución normal de media 5 y desviación típica 0.25.</p>
<p>Por ejemplo, si medimos los pesos de niños de 3 meses de edad que han pasado por una clínica pediátrica, podría ser que saliera la tabla anterior (en particular, el peso más repetido sería 4.96 kg). En ese caso diríamos que los pesos de los niños de 3 meses de edad que han pasado por esa clínica pediátrica siguen una distribución normal de media 5 kg y desviación típica 0.25 kg.</p>
<p>Obviamente, podemos decir que las medidas de un barra de 5 metros con una aparato cuya precisión es de 0.25 metros siguen una distribución normal de media 5 metros y desviación típica 0.25 metros.</p>
<p>Otros ejemplos serían:</p>
<ul>
<li>Cualquier medida de características naturales (altura, coeficiente de inteligencia, tensión arterial…) suele seguir una distribución normal.</li>
</ul>
</div>
</div>
<div id="la-distribución-de-poisson-esperar-2-horas-un-autobús-que-tiene-acordado-pasar-4-veces-cada-hora" class="section level3">
<h3>La distribución de Poisson: esperar 2 horas un autobús que tiene acordado pasar 4 veces cada hora</h3>
<p>Todo experimento consiste en realizar una actividad y, en el curso de ella, medir <em>algo</em>. Si repetimos el experimento muchas veces (o si lo realizamos sobre muchos individuos) vamos obteniendo una muestra de resultados. A este número de veces que se repite el experimento se le llama <strong>tamaño muestral</strong>.</p>
<p>En este caso:</p>
<ul>
<li>Actividad: Esperar 2 horas en una parada de un autobús que tiene previsto pasar 4 veces cada hora</li>
<li>Medida: contar cuántos autobuses realmente pasan.<br />
</li>
<li>Repeticiones del experimento: 10000 veces.</li>
</ul>
<p>La función “rpois” realiza el experimento por nosotros. Sus parámetros son:</p>
<ul>
<li><span class="math inline">\(\lambda\)</span>: resultado de multiplicar la frecuencia horaria acordada por el número de horas que vamos a esperar, es decir: 4 * 2 = 8.<br />
</li>
<li>n: número de veces que vamos a esperar 2 horas contando autobuses, que es 10000.</li>
</ul>
<pre class="r"><code>my_ = tamano_muestral
my_lambda = 4 * 2
muestra &lt;- rpois(n=my_n, lambda=my_lambda)</code></pre>
<p>No podemos mostrar los resultados de los 10000 experimentos pero sí de los primeros:</p>
<pre class="r"><code>head(muestra, 30)</code></pre>
<pre><code>##  [1] 13  9  8  7  6  7  9 10  9  7  1  8 12  7  8  5 12  3  6  5  9  7  9  4 14
## [26]  7  9 12  3 14</code></pre>
<p>Podemos recoger en una tabla cuantas veces ha salido cada resultado:</p>
<pre class="r"><code>df &lt;- data.frame(nro_autobuses = muestra) %&gt;% 
    group_by(nro_autobuses) %&gt;% 
    summarise(veces = n()) %&gt;%
    arrange(-veces)
df</code></pre>
<pre><code>## # A tibble: 20 x 2
##    nro_autobuses veces
##            &lt;int&gt; &lt;int&gt;
##  1             7  1443
##  2             8  1382
##  3             9  1247
##  4             6  1159
##  5            10  1037
##  6             5   901
##  7            11   716
##  8             4   571
##  9            12   483
## 10            13   308
## 11             3   272
## 12            14   160
## 13             2   115
## 14            15    90
## 15            16    43
## 16             1    32
## 17            17    27
## 18            18     8
## 19            19     4
## 20             0     2</code></pre>
<p>El histograma muestra, básicamente, esa tabla en forma gráfica:</p>
<pre class="r"><code>ggplot() + 
    geom_histogram(aes(x = muestra),
                   color = &quot;white&quot;, 
                   fill = &quot;orange&quot;, 
                   binwidth = 1) +
    labs(title = &quot;Histograma&quot;,
         x = &quot;Número de autobuses&quot;,
         y = &quot;Veces que hemos contado ese número de autobuses&quot;)</code></pre>
<p><img src="ley-grandes-numeros_files/figure-html/unnamed-chunk-18-1.png" width="672" /></p>
<p>Vemos que el resultado más repetido es 7, que ha ocurrido 1443 veces. Como el máximo de veces que podía repetirse era 10000, esto supone una proporción de 0.1443 o un porcentaje del 14.43%. A esta proporción se le llama <strong>frecuencia</strong> del resultado 7.</p>
<p>Podemos recoger en una tabla las frecuencias de todos los resultados. A esta tabla se la llama la <strong>distribución</strong> de resultados del experimento.</p>
<pre class="r"><code>distri_poi &lt;- mutate(df, frecuencia = round(veces / my_n,4))
distri_poi &lt;- select(distri_poi, nro_autobuses, frecuencia)
distri_poi</code></pre>
<pre><code>## # A tibble: 20 x 2
##    nro_autobuses frecuencia
##            &lt;int&gt;      &lt;dbl&gt;
##  1             7     0.144 
##  2             8     0.138 
##  3             9     0.125 
##  4             6     0.116 
##  5            10     0.104 
##  6             5     0.0901
##  7            11     0.0716
##  8             4     0.0571
##  9            12     0.0483
## 10            13     0.0308
## 11             3     0.0272
## 12            14     0.016 
## 13             2     0.0115
## 14            15     0.009 
## 15            16     0.0043
## 16             1     0.0032
## 17            17     0.0027
## 18            18     0.0008
## 19            19     0.0004
## 20             0     0.0002</code></pre>
<div id="abstracción-2" class="section level4">
<h4>Abstracción</h4>
<p>Cualquier experimento que se haga para medir <em>algo</em> producirá, en última instancia, una tabla de distribución de resultados. Más concisamente, se puede decir que todo experimento se resume en una distribución.</p>
<p>Si la distribución de un experimento coincide con la que acabamos de obtener (mismos resultados y misma frecuencia para cada resultado, salvo quizás el último decimal en algunos casos) diremos que el experimento indica que <em>lo que se está midiendo</em> sigue una distribución de Poisson de parámetro <span class="math inline">\(\lambda\)</span> = 4*2 = 8.</p>
<p>Por ejemplo, si medimos la edad de las personas ingresadas en un hospital podría ser que saliera la tabla anterior (los niños de 7 años serían, en particular, los más habituales). Diríamos que la edad de las personas internadas en ese hospital sigue una distribución de Poisson de parámetro <span class="math inline">\(\lambda\)</span> = 4*2 = 8.</p>
<p>Obviamente, podemos decir que el recuento durante 2 horas de los autobuses que llegan a una parada cuya frecuencia acordada es de 4 autobuses por hora sigue una distribución de Poisson de parámetro <span class="math inline">\(\lambda\)</span> = 4*2 = 8.</p>
<p>Otros ejemplos serían:</p>
<ul>
<li>El número de usuarios que accederán a una web de 9:00 a 17:00, si lo habitual es 15 usuarios por hora, sigue una distribución de Poisson de parámetro <span class="math inline">\(\lambda\)</span> = 15 * 8 = 120.<br />
</li>
<li>El número de errores que cometerá una mecanógrafa en las próximas 15 páginas que escriba, si habitualmente comete 2 errores cada 5 páginas, sigue una distribución de Poisson de parámetro <span class="math inline">\(\lambda\)</span> = 2/5 * 15 = 6.</li>
<li>El número de camisetas que venderá hoy una tienda, si lo habitual es 12 camisetas cada día, sigue una distribución de Poisson de parámetro <span class="math inline">\(\lambda\)</span> = 12*1 = 12.</li>
</ul>
</div>
</div>
<div id="la-ley-de-los-grandes-números" class="section level2">
<h2>La ley de los grandes números</h2>
<p>Lo que se puede ver en los experimentos anteriores es lo que dice la <strong>Ley de los grandes números</strong>:</p>
<ul>
<li><em>A partir de un tamaño muestral, posiblemente muy grande, es decir, a partir de cierto número de repeticiones del experimento, las tablas de distribución se estabilizan: mismos resultados y mismas frecuencias.</em></li>
</ul>
<p>En efecto, rehaciendo este documento una y otra vez se ve como las distribuciones son prácticamente las mismas, salvo quizás el último decimal en algunos casos. Y si aumentaramos el tamaño muestral coincidirían aun más.</p>
</div>




</div>

<script>

// add bootstrap table styles to pandoc tables
function bootstrapStylePandocTables() {
  $('tr.odd').parent('tbody').parent('table').addClass('table table-condensed');
}
$(document).ready(function () {
  bootstrapStylePandocTables();
});


</script>

<!-- tabsets -->

<script>
$(document).ready(function () {
  window.buildTabsets("TOC");
});

$(document).ready(function () {
  $('.tabset-dropdown > .nav-tabs > li').click(function () {
    $(this).parent().toggleClass('nav-tabs-open')
  });
});
</script>

<!-- code folding -->


<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    script.src  = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML";
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>

</body>
</html>
