{
    'aksépt':        ['aceptar', 'accept'],
    'aksépted':      ['aceptado', 'accepted'],
    'aláud':         ['permitido', 'allowed'],
    'and':           ['y', 'and'],
    'anlóful':       ['ilegal', 'unlawful'],
    'bi':            ['ser / estar', 'be'],
    'bráib':         ['soborno', 'bribe'],
    'chíldren':      ['niños', 'children'],
    'consént':       ['consentimiento', 'consent'],
    'críms':         ['helados (ice creams)', 'creams'],
    'der':           ['su', 'their'],
    'diplóid':       ['se distribuyó', 'deployed'],
    'dis':           ['estos', 'these'],
    'divélopmental': ['de desarrollo', 'developmental'],
    'doús':          ['esas / aquellas', 'those'],
    'dát':           ['eso', 'that'],
    'déi':           ['ellos / ellas', 'they'],
    'dídent':        ['no hicieron / no estuvo', "didn't"],
    'eféktiv':       ['eficaz', 'effective'],
    'eksperiméntal': ['experimental', 'experimental'],
    'enítáisment':   ['soborno / incentivo', 'enticement'],
    'güer':          ['fueron / estaban', 'were'],
    'gréit':         ['grandes', 'great'],
    'guíven':        ['nos dieron', 'given'],
    'güiz':          ['con', 'with'],
    'hamburguers':   ['hamburguesas', 'hamburgers'],
    'infórmed':      ['informado', 'informed'],
    'injékted':      ['inyectado', 'injected'],
    'invólved':      ['implicó', 'involved'],
    'inyékshon':     ['inyección', 'injection'],
    'iú':            ['tú / ustedes', 'you'],  
    'jamburguers':   ['hamburguesas', 'hamburgers'],
    'kampéin':       ['campaña', 'campaign'],
    'láis':          ['mentiras', 'lies'],
    'mánzs':         ['meses', 'months'],
    'mént':          ['significaba', 'meant'],
    'módifáid':      ['modificada', 'modified'],
    'mólekul':       ['molécula', 'molecule'],
    'nón':           ['ninguno', 'none'],
    'nót':           ['no', 'not'],
    'nóu':           ['saber / sabían', 'know'],
    'nyúro':         ['neuro', 'neuro'],
    'ólsóu':         ['también', 'also'],
    'ól':            ['todos', 'all'],
    'ónli':          ['solo', 'only'],
    'óperéishon':    ['operación', 'operation'],
    'parrt':         ['parte', 'part'],
    'périod':        ['período', 'period'],
    'próbably':      ['probablemente', 'probably'],
    'propagánda':    ['propaganda', 'propaganda'],
    'rísíved':       ['recibimos', 'received'],
    'riméin':        ['permanezca', 'remain'],
    'risíved':       ['recibimos', 'received'],
    'rikól':         ['recordarás', 'recall'],
    'séif':          ['seguro', 'safe'],
    'sámzing':       ['algo', 'something'],
    'sériess':       ['serie', 'series'],
    'séif':          ['seguro', 'safe'],
    'stándard':      ['estándar', 'standard'],
    'stándard':      ['estándar', 'standard'],
    'stéiting':      ['decir / declarar', 'stating'],
    'stéi':          ['quedarse', 'stay'],
    'táim':          ['tiempo', 'time'],
    'tóuld':         ['dijeron', 'told'],
    'trúli':         ['realmente', 'truly'],
    'trúz':          ['verdad', 'truth'],
    'uér':           ['eran / fueron / dónde', 'were / where'],
    'uidáut':        ['sin', 'without'],
    'únder':         ['bajo', 'under'],
    'vaksinéited':   ['vacunados', 'vaccinated'],
    'wí':            ['nosotros', 'we'],
    'wíks':          ['semanas', 'weeks'],
    'yábs':          ['pinchazos', 'jabs'],
    'yústifái':      ['justificar', 'justify'],
    'úer':           ['eran / fueron / dónde', 'were / where']
}
