{
    'aksépt': ['aceptar', 'accept', 'General'],
    'aksépted': ['aceptado', 'accepted', 'General'],
    'aláud': ['permitido', 'allowed', 'General'],
    'and': ['y', 'and', 'General'],
    'anlóful': ['ilegal', 'unlawful', 'General'],
    'bi': ['ser / estar', 'be', 'General'],
    'bráib': ['soborno', 'bribe', 'General'],
    'chíldren': ['niños', 'children', 'General'],
    'consént': ['consentimiento', 'consent', 'General'],
    'crím': ['helado (ice cream)', 'cream', 'General'],
    'der': ['su', 'their', 'General'],
    'diplóid': ['se distribuyó', 'deployed', 'General'],
    'dis': ['estos', 'these', 'General'],
    'divélopmental': ['de desarrollo', 'developmental', 'General'],
    'doús': ['esas / aquellas', 'those', 'General'],
    'dát': ['eso', 'that', 'General'],
    'déi': ['ellos / ellas', 'they', 'General'],
    'dídent': ['no hicieron / no estuvo', "didn't", 'General'],
    'eféktiv': ['eficaz', 'effective', 'General'],
    'eksperiméntal': ['experimental', 'experimental', 'General'],
    'entáisment': ['soborno / incentivo', 'enticement', 'General'],
    'gréit': ['grandes', 'great', 'General'],
    'guíven': ['nos dieron', 'given', 'General'],
    'infórmed': ['informado', 'informed', 'General'],
    'injékted': ['inyectado', 'injected', 'General'],
    'invólved': ['implicó', 'involved', 'General'],
    'inyékshon': ['inyección', 'injection', 'General'],
    'iú': ['tú / ustedes', 'you', 'General'],
    'jamburguers': ['hamburguesas', 'hamburgers', 'General'],
    'kampéin': ['campaña', 'campaign', 'General'],
    'láis': ['mentiras', 'lies', 'General'],
    'mánzs': ['meses', 'months', 'General'],
    'mént': ['significaba', 'meant', 'General'],
    'módifáid': ['modificada', 'modified', 'General'],
    'mólekul': ['molécula', 'molecule', 'General'],
    'nyúro': ['neuro', 'neuro', 'General'],
    'nón': ['ninguno', 'none', 'General'],
    'nót': ['no', 'not', 'General'],
    'nóu': ['saber / sabían', 'know', 'General'],
    'part': ['parte', 'part', 'General'],
    'propagánda': ['propaganda', 'propaganda', 'General'],
    'próbably': ['probablemente', 'probably', 'General'],
    'périod': ['período', 'period', 'General'],
    'rikól': ['recordarás', 'recall', 'General'],
    'riméin': ['permanezca', 'remain', 'General'],
    'risíved': ['recibimos', 'received', 'General'],
    'stándard': ['estándar', 'standard', 'General'],
    'stéi': ['quedarse', 'stay', 'General'],
    'stéiting': ['decir / declarar', 'stating', 'General'],
    'sámzing': ['algo', 'something', 'General'],
    'séif': ['seguro', 'safe', 'General'],
    'sériess': ['serie', 'series', 'General'],
    'trúli': ['realmente', 'truly', 'General'],
    'trúz': ['verdad', 'truth', 'General'],
    'táim': ['tiempo', 'time', 'General'],
    'tóuld': ['dijeron', 'told', 'General'],
    'uidáut': ['sin', 'without', 'General'],
    'uiz': ['con', 'with', 'General'],
    'uér': ['eran / fueron / dónde', 'were / where', 'General'],
    'uí': ['nosotros', 'we', 'General'],
    'uíks': ['semanas', 'weeks', 'General'],
    'vaksinéited': ['vacunados', 'vaccinated', 'General'],
    'yábs': ['pinchazos', 'jabs', 'General'],
    'yústifái': ['justificar', 'justify'],
    'ól': ['todos', 'all', 'General'],
    'ólsóu': ['también', 'also', 'General'],
    'ónli': ['solo', 'only', 'General'],
    'óperéishon': ['operación', 'operation', 'General'],
    'únder': ['bajo', 'under', 'General'],
}
